version: '3'
services:
  postgresql:
    image: postgres:latest
    environment:
     - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
     - "5432:5432"
    volumes:
     - postgresql-data:/var/lib/postgresql/data
volumes:
  postgresql-data: