version: '3'
services:
  mongo:
    image: "mongo:latest"
    ports:
     - "27017:27017"
    volumes:
     - mongo-data:/data/db

  postgresql:
    image: postgres:latest
    environment:
     - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
     - "5432:5432"
    volumes:
     - postgresql-data:/var/lib/postgresql/data

  redis:
    image: "redis:latest"
    ports:
     - "6379:6379"
    volumes:
     - redis-data:/data
    command: redis-server --requirepass redisPassword   

volumes:
  mongo-data:
  postgresql-data:
  redis-data: