version: '3'
services:
  ibm-mq:
    image: "ibmcom/mq"
    ports:
    - "1414:1414"
    - "9443:9443"
    environment:
    - LICENSE=accept
    - MQ_QMGR_NAME=QM1
    - MQ_ADMIN_PASSWORD=passw0rd
    volumes:
     - ibmmq-data:/mnt/mqm
volumes:
  ibmmq-data:     